'use strict';

module.exports = {
  
  /* VALIDATION CONSTANTS */
  MIN_EMAIL_LENGTH: 1,
  MAX_EMAIL_LENGTH: 100,
  MIN_PASSWORD_LENGTH: 8,
  MAX_PASSWORD_LENGTH: 16,
  PASSWORD_REGEX: /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])[a-zA-Z\d]*$/,

  /* RESPONSE ERROR CODES */
  ERROR_BAD_REQUEST: 400,
  ERROR_UNAUTHORIZED: 401,
  ERROR_FORBIDDEN: 403,
  ERROR_NOT_FOUND: 404,
  ERROR_INTERNAL_SERVER: 500,
  ERROR_NOT_IMPLEMENTED: 501,
  
  /* MONGODB ERROR CODES */
  ERROR_MONGODB_DUPLICATE: 11000,
};
